RISCV ?= /usr
TARGET = test_fb
AS = riscv64-unknown-elf-as
LD = riscv64-unknown-elf-ld
OBJCOPY = riscv64-unknown-elf-objcopy

all: $(TARGET).bin

$(TARGET).o: $(TARGET).S
	$(AS) -march=rv32ima -mabi=ilp32 $< -o $@

$(TARGET).elf: $(TARGET).o
	$(LD) -m elf32lriscv -Ttext=0x0 $< -o $@

$(TARGET).bin: $(TARGET).elf
	$(OBJCOPY) -O binary $< $@

clean:
	rm -f $(TARGET).o $(TARGET).elf $(TARGET).bin

.PHONY: all clean